### ISSUE TITLE
Unable to use action with merged pull request trigger

### ISSUE THREAD

**Issue by gardar** [patrickjahns/version-drafter-action#341]
When I try to use the action with the [following configuration](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request-workflow-when-a-pull-request-merges)

```yaml
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.mer
```

the action just exists silently, it doesn't fail or set any outputs or even log any error messages, which makes it hard to diagnose what's causing it to fail.

Any ideas?
